### ISSUE TITLE
Any mathematical changes or changes in principle with new version?

### ISSUE THREAD

**Issue by DennisFeige** [CFeregrino/scWGCNA#13]
Hi @CFeregrino,

I used the version of the package before the last update (scWGCNA_0.1.0 ) and saw that you updated the package quite nicely! Because I wanted to access the figures and some raw data under the last version, I basically copied out the R code of the html output and modified it a bit for my purposes. Did anything change mathematically or in the principle of analysis with the latest update? So basically, will the new version give me the same results as the old version?

Best,
Dennis

**Comment by CFeregrino** [comment]
In principle, everything stays the same. The only major differencewould be the way I cut down modules to merge very similar modules and remove modules expressed in very few cells.
Otherwise you can always refer to the version 0.1.0, and in the new version, all the old functions still exist and work in the same way.

**Comment by DennisFeige** [comment]
Thanks very much @CFeregrino !!
Goof to know
